### ISSUE TITLE
UI Layout

### ISSUE THREAD

**Issue by taehwanhong** [taehwanhong/JinnyCast#3]
HTML Structure 완성

**Comment by sujinleeme** [comment]
@taehwanhong 클래스명 수정했습니다. 
* 미디어 플레이어 재생 - `id="get_view"를 class="youtubeMedia`변경
* 페이지 이동 `id="nav_view"`를 `class="pagination"`로 변경

**Comment by sujinleeme** [comment]
dev1.3.1에 반영 완료
